### ISSUE TITLE
Figure out how the index progress numbers correlate

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-first-aid-kit#4]
I just tried deleting my links2 dir, ran `sbot start` and let it run for a little bit. This is a screenshot of it running

![image](https://user-images.githubusercontent.com/1427063/68396142-56f43a80-0171-11ea-98a4-9cf8a11805e1.png)

Surprising things:
1. I would have expected `current == links2`. Is `current` some kind of average? Plain average of all the indexes is `730169488.375` (quadratic mean `~739477572`) which is close but not it. However, if we can just assume that it's *some* average then that's probably good enough for our purposes.
2. I would have expected `start` to be 0 or close to it.

Not gonna dwell on this too long since I don't need to but would be nice to know. Do you have any ideas @mixmix ?

**Comment by dominictarr** [comment]
code is here:
https://github.com/ssbc/ssb-db/blob/80af97584f7700661a63fa6065885641911443ae/db.js#L21-L42

but it's only updated every 200 ms, but the numbers under `since.plugins` are exact at the time you call `status`. so it makes sense that the `progress.indexes.current` is slightly lower than the true average.

**Comment by Powersource** [comment]
Ah, thanks for the explanation :)

**Comment by Powersource** [comment]
Linking here from the code now
